
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class usersignup extends javax.swing.JFrame {

    
    public usersignup() {
        initComponents();
        setSize(1000,700);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        confirm = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        email.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(email);
        email.setBounds(630, 190, 170, 35);

        user.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(user);
        user.setBounds(630, 130, 170, 35);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 200, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 140, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 260, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 320, 110, 20);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 420, 100, 23);

        pass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(pass);
        pass.setBounds(630, 250, 170, 35);

        confirm.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(confirm);
        confirm.setBounds(630, 310, 170, 35);

        jButton2.setText("LogIn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 470, 120, 23);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SignUp");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(640, 40, 150, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background and icons/Webp.net-resizeimage (13).jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 0, 640, 700);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background and icons/Webp.net-resizeimage (5).jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String a,b,e,o;
       
       a=user.getText();
       b=pass.getText();
       o=confirm.getText();
       e=email.getText();
       
       
       if(a.equals("")||b.equals("")||e.equals(""))
       {
           JOptionPane.showMessageDialog(this,"All fields are mandatory");
           
       }
       else
       {
       if(!e.contains("@")||!e.contains(".")||!e.contains("com"))
       {
            JOptionPane.showMessageDialog(this,"Invalid email");
       }
       
       if(b.equals(o))
       {
           try
       {
        HttpResponse<String> response=Unirest.get(GlobalData.hostname+"/usersignup")
                                           .queryString("username",a)
                                           .queryString("password",b)
                                           .queryString("email",e)
                                           .asString();
         if(response.getBody().equals("User SignUp Successful"))
         {
             new userlogin().setVisible(true);
         }
         else
         {
             JOptionPane.showMessageDialog(this,"Username already taken");
         }
         
               
    }                                        
    catch( UnirestException | HeadlessException ex)
    {
       ex.printStackTrace();
    }
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Confirm password and password should be same");
       }
       }
     
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new userlogin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
           java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                   new usersignup().setVisible(true);
               }
           });
       } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
           Logger.getLogger(usersignup.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
